apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 233422680010.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:b91f7ec222a3225b4ae7d0df146e0a3841af62d8
        ports:
        - containerPort: 80
