apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 233422680010.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:013da4a8d403771c285c1160e3e235f4266996bf
          ports:
            - containerPort: 5000
