apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 233422680010.dkr.ecr.us-east-1.amazonaws.com/shopping-site-main:b6cd179623631d2114b489dd3124928d00add64e
        ports:
        - containerPort: 80

