apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 233422680010.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:dfb2662d0987865778c7e2345cfdbbb804cba65a
        ports:
        - containerPort: 80
