apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 233422680010.dkr.ecr.us-east-1.amazonaws.com/shopping-site-computers:013da4a8d403771c285c1160e3e235f4266996bf
        ports:
        - containerPort: 80
