apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 233422680010.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:5bf2d7d97ee174975d0debd9bd6b314e89ed808e
        ports:
        - containerPort: 80
